version: '3.8'

services:
  app:
    image: roydebraj2003/link-shortener-app:v1.0
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: somepassword
      DB_NAME: link_shortener
      REDIS_HOST: redis
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: somepassword
      POSTGRES_DB: link_shortener
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d link_shortener"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: always

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
